### ISSUE TITLE
使用fofa 获取不到代理是什么原因啊？

### ISSUE THREAD

**Issue by junanc** [sh1yan/Sppmagic#1]
<img width="463" alt="image" src="https://github.com/sh1yan/Sppmagic/assets/44342736/648bc6ec-a387-4a6b-bbd8-56bf3c8c293b">

**Comment by sh1yan** [comment]
fofa首次采集到的2000个地址中，验活成功1个，在正常使用后发现该已验活的代理地址无法正常使用，程序会把该已验活的地址从存活代理数组中去掉，然后挂载等待60秒，等fofa进行第二次API采集socks5代理，再继续验活使用。由于第一轮采集中你这里只发现存在1个能正常使用，然后实际代理使用时发现无法使用，导致当前没有无法使用的代理地址。你再等待60秒吧， 看看后续的采集中是否能采集到可用的socks5代理地址吧。

**Comment by junanc** [comment]
不行，一直卡在这里了 show all  这个命令也只能成功执行一次， 在次执行 或者其他命令 都没回显了  exit  都没有反应了。就一直是截图的这个样子。等了一个小时 都还是这样没有变化。 exit 退出都退出不了。 只能强制结束

**Comment by sh1yan** [comment]
你要不用原版的 https://github.com/Ggasdfg321/SmallProxyPool 的试试，看看存不存这个问题，他这fofa的功能模块代码我都基本没改动，我由于没有API权限，我只对我native采集和quake的采集进行debug都没问题的。
